[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev && npm install && npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
APP_NAME = "EduNexus"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://edunexus-production.up.railway.app"
APP_KEY = "base64:krkXSJV994O19uweOXc004bOa/4MsEUEgHrvWmSPOzk="

# Database Configuration
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"

# Regional Databases
DB_DHAKA_DATABASE = "edunexus_Dhaka"
DB_DHAKA_USERNAME = "${MYSQLUSER}"
DB_DHAKA_PASSWORD = "${MYSQLPASSWORD}"

DB_KHULNA_DATABASE = "edunexus_Khulna"
DB_KHULNA_USERNAME = "${MYSQLUSER}"
DB_KHULNA_PASSWORD = "${MYSQLPASSWORD}"

DB_RAJSHAHI_DATABASE = "edunexus_Rajsahi"
DB_RAJSHAHI_USERNAME = "${MYSQLUSER}"
DB_RAJSHAHI_PASSWORD = "${MYSQLPASSWORD}"

# Session and Cache
SESSION_DRIVER = "database"
CACHE_STORE = "database"
QUEUE_CONNECTION = "database"

# Mail Configuration
MAIL_MAILER = "smtp"
MAIL_HOST = "smtp.mailtrap.io"
MAIL_PORT = "2525"
MAIL_USERNAME = "${MAIL_USERNAME}"
MAIL_PASSWORD = "${MAIL_PASSWORD}"
MAIL_ENCRYPTION = "tls"
MAIL_FROM_ADDRESS = "hello@edunexus.com"
MAIL_FROM_NAME = "EduNexus"

# Stripe Configuration
STRIPE_KEY = "${STRIPE_KEY}"
STRIPE_SECRET = "${STRIPE_SECRET}"
